### ISSUE TITLE
returns no_app_context (Slack::Web::Api::Errors::SlackError) when using chat_scheduleMessage

### ISSUE THREAD

**Issue by MarioRuiz** [slack-ruby/slack-ruby-client#278] opened 2019-07-01 14:12 UTC
I am trying to use the schedule endpoint but not lucky. I am able to use any other end point like users_info or conversations_members but when using chat_scheduleMessage
`wclient.chat_scheduleMessage(channel: dchannel, as_user: true, text: message, post_at: time)`

I get the error no_app_context:
`/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slack-ruby-client-0.14.2/lib/slack/web/faraday/response/raise_error.rb:11:in `on_complete'
/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/request/url_encoded.rb:15:in `call'
/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/request/multipart.rb:15:in `call'
/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:175:in `post'
/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slack-ruby-client-0.14.2/lib/slack/web/faraday/request.rb:25:in `request'
/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slack-ruby-client-0.14.2/lib/slack/web/faraday/request.rb:10:in `post'
/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slack-ruby-client-0.14.2/lib/slack/web/api/endpoints/chat.rb:222:in `chat_scheduleMessage'
`

**Comment by dblock** [comment] 2019-07-01 22:43
This is a question for Slack API support, the `no_app_context` error isn't even listed in https://api.slack.com/methods/chat.scheduleMessage. The library just passes messages to slack without overthinking it ;) 

I'll close this for now, but feel free to reopen if you feel like the problem is in the client. Let us know what they say?

**Closed by dblock** 2019-07-01 22:43 UTC

**Comment by MarioRuiz** [comment] 2019-07-05 15:39
They responded that legacy bots are not allowed to use chat.scheduleMessage and also that legacy bots will be deprecated any time
https://api.slack.com/custom-integrations/bot-users

**Comment by dblock** [comment] 2019-07-05 15:47
What's a "legacy bot"?

**Comment by MarioRuiz** [comment] 2019-07-05 16:44
According to them the bots now need to follow:
https://api.slack.com/bot-users
The others are legacy bots
