### ISSUE TITLE
Slack::Web::Api::Errors::SlackError - channel_not_found

### ISSUE THREAD

**Issue by janklimo** [slack-ruby/slack-ruby-client#227] opened 2018-09-25 17:16 UTC
I have a bot listening to slash commands. My scopes are `commands,chat:write:bot`. I'm posting a response to the received `channel_id` as follows:

```ruby
client.chat_postMessage(
  channel: params['channel_id'],
  text: 'some text'
)
```

All works fine except when the user triggers the slash command from a private message (`"channel_id"=>"D3YJxxx25", "channel_name"=>"directmessage"`). That results in `Slack::Web::Api::Errors::SlackError - channel_not_found`.

Am I missing the right scope or something else? Many thanks!

**Comment by dblock** [comment] 2018-09-25 19:50
Looks correct to me, but seems like a channel ID is invalid unless you opened the DM yourself? I think this is more of a question to Slack API people, we're just the messenger here :) 

I'll close the issue, but do post what you find please.

**Closed by dblock** 2018-09-25 19:50 UTC

**Comment by jmanian** [comment] 2018-09-25 23:36
@janklimo I suspect the issue is that the user is invoking the slash command in a DM with another user. Your problem then would be that your app is not a member of the DM (in fact the app itself cannot be a member of a DM) so it does not have permission to post in the DM.

If I recall there are other ways other than `chat.postMessage` to post follow-ups to slash commands. For an invocation in a DM that might be your only option. But I haven't messed with slash commands in a while so I'm not sure.

I suggest you join this Slack workspace and inquire there: https://community.botkit.ai/

**Comment by dblock** [comment] 2018-09-26 00:14
You can respond to a slash command with text without doing a `chat_postMessage`, I think that's the only way for it to work.
